### ISSUE TITLE
bubble sort implementatin for py

### ISSUE THREAD

**Issue by vidhanshu** [vidhanshu/DSA-Hacktoberfest#1]

**Comment by ashishpetwal** [comment]
please assign this issue to me!

**Comment by snnath** [comment]
Im up for this task. Please assign.

**Comment by ArSin2002** [comment]
i would love to work on this @vidhanshu 
please assign this to me

**Comment by ashishpetwal** [comment]
@vidhanshu can you please close this issue now !

**Comment by ashishpetwal** [comment]
Also @vidhanshu kindly add "hacktoberfest" or "hacktoberfest-accepted" label in your repo
