### ISSUE TITLE
add search algorithm

### ISSUE THREAD

**Issue by vidhanshu** [vidhanshu/DSA-Hacktoberfest#11]

**Comment by Tejas20-03** [comment]
It will be my pleasure to work on above issue

**Comment by JayantVashishtha** [comment]
I would like to contribute in this task.

**Comment by snnath** [comment]
Im interested to work on this!!!

**Comment by vidhanshu** [comment]
@snnath 
@JayantVashishtha 

you can open other issues too. by yourself i would assign to you guys!

**Comment by Tejas20-03** [comment]
@vidhanshu Hey can u pls let me know which search algorithm u want and in which language?

**Comment by vidhanshu** [comment]
linear or binary or any one you want to add
any language

**Comment by naveenbisht31** [comment]
Hey, I would like to contribute (Binary Search). Please assign it to me.

**Comment by geoffgeorgein** [comment]
hey, I can contribute a linear search algorithm in C++.Please assign me.

**Comment by sambhavgupta0705** [comment]
Can I also work on this isse by adding linear search

**Comment by 55ritesh** [comment]
please assign this to me

**Comment by yogesh-9999** [comment]
hi @vidhanshu  please assign me this issue
