### ISSUE TITLE
Implement Linear search in python

### ISSUE THREAD

**Issue by vidhanshu** [vidhanshu/DSA-Hacktoberfest#47]

**Comment by IAMBANN** [comment]
Hi @vidhanshu 
can you assign me this issue as i am new to open source. I want to give it a try

**Comment by IAMBANN** [comment]
i have added linear search and raised a PR  https://github.com/vidhanshu/DSA-Hacktoberfest/pull/63

**Comment by gautamV19** [comment]
Can you please assign this issue to me?
