### ISSUE TITLE
Implement Binary search in java

### ISSUE THREAD

**Issue by vidhanshu** [vidhanshu/DSA-Hacktoberfest#51]

**Comment by Abhirv08** [comment]
@vidhanshu  Assign it to me. I can do this.

**Comment by manishtambe** [comment]
@vidhanshu I can do it in java can you please assign it to me ?

**Comment by Abhirv08** [comment]
@vidhanshu I have to write algorithm to perform Binary Search. I mean how it's code is written, right?

**Comment by Shreyaww** [comment]
Can you please assign this issue to me as this would be my first contribution in hacktoberfest

**Comment by vidhanshu** [comment]
> Can you please assign this issue to me as this would be my first contribution in hacktoberfest

It's already been implemented please create a PR with with new issue, I'll assign it to you!
